# Generated by Django 3.2.6 on 2021-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the effect.', max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('effect_file', models.FileField(upload_to='effects/')),
            ],
            options={
                'verbose_name': 'Effect',
                'verbose_name_plural': 'Effects',
            },
        ),
    ]
