# Generated by Django 3.2.6 on 2021-08-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightStrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the light strip.', max_length=200)),
                ('num_pixels', models.IntegerField(help_text='The number of neopixels on the light strip.')),
                ('pwm_pin', models.IntegerField(help_text='The pin the strip is connected to on the Raspberry Pi.')),
            ],
            options={
                'verbose_name': 'Light Strip',
                'verbose_name_plural': 'Light Strips',
            },
        ),
    ]
