# Generated by Django 3.2.6 on 2021-08-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lightstrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenEffects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('strip', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Open Effect',
                'verbose_name_plural': 'Open Effects',
            },
        ),
    ]
