# Generated by Django 3.2.6 on 2021-08-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_openeffects'),
    ]

    operations = [
        migrations.AddField(
            model_name='openeffects',
            name='processes',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
    ]
